services:
  app:
    profiles:
      - app
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_USER=scanner_user
      - DB_PASSWORD=scanner_pass
      - DB_NAME=github_scanner
      - DB_PORT=5432
      - REDIS_ADDR=redis:6379

      - APP_ENV
      - LOG_LEVEL
      - GITHUB_TOKEN
      - GITHUB_TIMEOUT_SECONDS
      - GITHUB_CACHE_TTL_SECONDS
      - GITHUB_CACHE_ERROR_TTL_SECONDS

      - SCANNER_WORKERS
      - SCANNER_QUEUE_SIZE
      - SCANNER_SAFETY_BUFFER
      - SCANNER_PRODUCER_INTERVAL_SECONDS
      - SCANNER_MIN_INTERVAL_SECONDS

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  mailer:
    profiles:
      - app
    build:
      context: .
      dockerfile: Dockerfile
      target: mailer
    environment:
      - REDIS_ADDR=redis:6379

      - APP_ENV
      - MAILER_WORKERS
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_USER
      - SMTP_PASS
      - SMTP_FROM
      - SMTP_SENDER_EMAIL

    depends_on:
      redis:
        condition: service_healthy

  test:
    profiles:
      - test
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    command: go test -v -tags="unit,integration" ./...
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: scanner_user
      POSTGRES_PASSWORD: scanner_pass
      POSTGRES_DB: github_scanner
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scanner_user -d github_scanner"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
