// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: mailer/v1/mailer.proto

package mailerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// mirrors internal/infra/mq.EventType
type EmailType int32

const (
	EmailType_EMAIL_TYPE_UNSPECIFIED        EmailType = 0
	EmailType_EMAIL_TYPE_NEW_RELEASE        EmailType = 1
	EmailType_EMAIL_TYPE_REPO_MOVED         EmailType = 2
	EmailType_EMAIL_TYPE_EMAIL_VERIFICATION EmailType = 3
)

// Enum value maps for EmailType.
var (
	EmailType_name = map[int32]string{
		0: "EMAIL_TYPE_UNSPECIFIED",
		1: "EMAIL_TYPE_NEW_RELEASE",
		2: "EMAIL_TYPE_REPO_MOVED",
		3: "EMAIL_TYPE_EMAIL_VERIFICATION",
	}
	EmailType_value = map[string]int32{
		"EMAIL_TYPE_UNSPECIFIED":        0,
		"EMAIL_TYPE_NEW_RELEASE":        1,
		"EMAIL_TYPE_REPO_MOVED":         2,
		"EMAIL_TYPE_EMAIL_VERIFICATION": 3,
	}
)

func (x EmailType) Enum() *EmailType {
	p := new(EmailType)
	*p = x
	return p
}

func (x EmailType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EmailType) Descriptor() protoreflect.EnumDescriptor {
	return file_mailer_v1_mailer_proto_enumTypes[0].Descriptor()
}

func (EmailType) Type() protoreflect.EnumType {
	return &file_mailer_v1_mailer_proto_enumTypes[0]
}

func (x EmailType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EmailType.Descriptor instead.
func (EmailType) EnumDescriptor() ([]byte, []int) {
	return file_mailer_v1_mailer_proto_rawDescGZIP(), []int{0}
}

// mirrors internal/infra/mq.DeliveryMessage
type DeliveryCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EmailType              `protobuf:"varint,1,opt,name=type,proto3,enum=mailer.v1.EmailType" json:"type,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Repo          string                 `protobuf:"bytes,3,opt,name=repo,proto3" json:"repo,omitempty"`
	Release       string                 `protobuf:"bytes,4,opt,name=release,proto3" json:"release,omitempty"`
	Payload       map[string]string      `protobuf:"bytes,5,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryCommand) Reset() {
	*x = DeliveryCommand{}
	mi := &file_mailer_v1_mailer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryCommand) ProtoMessage() {}

func (x *DeliveryCommand) ProtoReflect() protoreflect.Message {
	mi := &file_mailer_v1_mailer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryCommand.ProtoReflect.Descriptor instead.
func (*DeliveryCommand) Descriptor() ([]byte, []int) {
	return file_mailer_v1_mailer_proto_rawDescGZIP(), []int{0}
}

func (x *DeliveryCommand) GetType() EmailType {
	if x != nil {
		return x.Type
	}
	return EmailType_EMAIL_TYPE_UNSPECIFIED
}

func (x *DeliveryCommand) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *DeliveryCommand) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *DeliveryCommand) GetRelease() string {
	if x != nil {
		return x.Release
	}
	return ""
}

func (x *DeliveryCommand) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SendResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivered     bool                   `protobuf:"varint,1,opt,name=delivered,proto3" json:"delivered,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResult) Reset() {
	*x = SendResult{}
	mi := &file_mailer_v1_mailer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResult) ProtoMessage() {}

func (x *SendResult) ProtoReflect() protoreflect.Message {
	mi := &file_mailer_v1_mailer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResult.ProtoReflect.Descriptor instead.
func (*SendResult) Descriptor() ([]byte, []int) {
	return file_mailer_v1_mailer_proto_rawDescGZIP(), []int{1}
}

func (x *SendResult) GetDelivered() bool {
	if x != nil {
		return x.Delivered
	}
	return false
}

func (x *SendResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_mailer_v1_mailer_proto protoreflect.FileDescriptor

const file_mailer_v1_mailer_proto_rawDesc = "" +
	"\n" +
	"\x16mailer/v1/mailer.proto\x12\tmailer.v1\"\xfe\x01\n" +
	"\x0fDeliveryCommand\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.mailer.v1.EmailTypeR\x04type\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04repo\x18\x03 \x01(\tR\x04repo\x12\x18\n" +
	"\arelease\x18\x04 \x01(\tR\arelease\x12A\n" +
	"\apayload\x18\x05 \x03(\v2'.mailer.v1.DeliveryCommand.PayloadEntryR\apayload\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"B\n" +
	"\n" +
	"SendResult\x12\x1c\n" +
	"\tdelivered\x18\x01 \x01(\bR\tdelivered\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason*\x81\x01\n" +
	"\tEmailType\x12\x1a\n" +
	"\x16EMAIL_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16EMAIL_TYPE_NEW_RELEASE\x10\x01\x12\x19\n" +
	"\x15EMAIL_TYPE_REPO_MOVED\x10\x02\x12!\n" +
	"\x1dEMAIL_TYPE_EMAIL_VERIFICATION\x10\x032\x8f\x01\n" +
	"\rMailerService\x129\n" +
	"\x04Send\x12\x1a.mailer.v1.DeliveryCommand\x1a\x15.mailer.v1.SendResult\x12C\n" +
	"\n" +
	"SendStream\x12\x1a.mailer.v1.DeliveryCommand\x1a\x15.mailer.v1.SendResult(\x010\x01B\xc5\x01\n" +
	"\rcom.mailer.v1B\vMailerProtoP\x01Zbgithub.com/GenesisEducationKyiv/software-engineering-school-6-0-ddmytro-m/proto/mailer/v1;mailerv1\xa2\x02\x03MXX\xaa\x02\tMailer.V1\xca\x02\tMailer\\V1\xe2\x02\x15Mailer\\V1\\GPBMetadata\xea\x02\n" +
	"Mailer::V1b\x06proto3"

var (
	file_mailer_v1_mailer_proto_rawDescOnce sync.Once
	file_mailer_v1_mailer_proto_rawDescData []byte
)

func file_mailer_v1_mailer_proto_rawDescGZIP() []byte {
	file_mailer_v1_mailer_proto_rawDescOnce.Do(func() {
		file_mailer_v1_mailer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mailer_v1_mailer_proto_rawDesc), len(file_mailer_v1_mailer_proto_rawDesc)))
	})
	return file_mailer_v1_mailer_proto_rawDescData
}

var file_mailer_v1_mailer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mailer_v1_mailer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_mailer_v1_mailer_proto_goTypes = []any{
	(EmailType)(0),          // 0: mailer.v1.EmailType
	(*DeliveryCommand)(nil), // 1: mailer.v1.DeliveryCommand
	(*SendResult)(nil),      // 2: mailer.v1.SendResult
	nil,                     // 3: mailer.v1.DeliveryCommand.PayloadEntry
}
var file_mailer_v1_mailer_proto_depIdxs = []int32{
	0, // 0: mailer.v1.DeliveryCommand.type:type_name -> mailer.v1.EmailType
	3, // 1: mailer.v1.DeliveryCommand.payload:type_name -> mailer.v1.DeliveryCommand.PayloadEntry
	1, // 2: mailer.v1.MailerService.Send:input_type -> mailer.v1.DeliveryCommand
	1, // 3: mailer.v1.MailerService.SendStream:input_type -> mailer.v1.DeliveryCommand
	2, // 4: mailer.v1.MailerService.Send:output_type -> mailer.v1.SendResult
	2, // 5: mailer.v1.MailerService.SendStream:output_type -> mailer.v1.SendResult
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mailer_v1_mailer_proto_init() }
func file_mailer_v1_mailer_proto_init() {
	if File_mailer_v1_mailer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mailer_v1_mailer_proto_rawDesc), len(file_mailer_v1_mailer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mailer_v1_mailer_proto_goTypes,
		DependencyIndexes: file_mailer_v1_mailer_proto_depIdxs,
		EnumInfos:         file_mailer_v1_mailer_proto_enumTypes,
		MessageInfos:      file_mailer_v1_mailer_proto_msgTypes,
	}.Build()
	File_mailer_v1_mailer_proto = out.File
	file_mailer_v1_mailer_proto_goTypes = nil
	file_mailer_v1_mailer_proto_depIdxs = nil
}
